"""Add health_events and reminders tables

Revision ID: 1c6d8ff59306
Revises: 3279c7654f82
Create Date: 2025-12-09 03:57:50.203168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6d8ff59306'
down_revision: Union[str, None] = '3279c7654f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('VACCINATION', 'TREATMENT', 'CHECKUP', 'ILLNESS', name='eventtype'), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('administration_route', sa.Enum('SUBCUTANEA', 'INTRAMUSCULAR', 'ORAL', 'INTRAVENOSA', name='administrationroute'), nullable=False),
    sa.Column('next_dose_date', sa.Date(), nullable=True),
    sa.Column('treatment_end_date', sa.Date(), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('veterinarian_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_application_date'), 'health_events', ['application_date'], unique=False)
    op.create_index(op.f('ix_health_events_cattle_id'), 'health_events', ['cattle_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=True),
    sa.Column('health_event_id', sa.UUID(), nullable=True),
    sa.Column('reminder_type', sa.Enum('VACCINE', 'CHECKUP', 'TREATMENT', 'GENERAL', name='remindertype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['health_event_id'], ['health_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_cattle_id'), 'reminders', ['cattle_id'], unique=False)
    op.create_index(op.f('ix_reminders_health_event_id'), 'reminders', ['health_event_id'], unique=False)
    op.create_index(op.f('ix_reminders_reminder_date'), 'reminders', ['reminder_date'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_reminder_date'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_health_event_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_cattle_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_health_events_cattle_id'), table_name='health_events')
    op.drop_index(op.f('ix_health_events_application_date'), table_name='health_events')
    op.drop_table('health_events')
    # ### end Alembic commands ###
