"""Initial migration with cattle and ranches

Revision ID: 3279c7654f82
Revises: 
Create Date: 2025-12-07 15:54:21.794702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3279c7654f82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('size_hectares', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranches_owner_id'), 'ranches', ['owner_id'], unique=False)
    op.create_table('cattle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ranch_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('lot', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DECEASED', 'QUARANTINE', name='cattlestatus'), nullable=False),
    sa.Column('reproductive_status', sa.Enum('EMPTY', 'PREGNANT', 'LACTATING', 'DRY', name='reproductivestatus'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('last_birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ranch_id'], ['ranches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cattle_lot'), 'cattle', ['lot'], unique=False)
    op.create_index(op.f('ix_cattle_owner_id'), 'cattle', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cattle_tag_number'), 'cattle', ['tag_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cattle_tag_number'), table_name='cattle')
    op.drop_index(op.f('ix_cattle_owner_id'), table_name='cattle')
    op.drop_index(op.f('ix_cattle_lot'), table_name='cattle')
    op.drop_table('cattle')
    op.drop_index(op.f('ix_ranches_owner_id'), table_name='ranches')
    op.drop_table('ranches')
    # ### end Alembic commands ###
